### ISSUE TITLE
Typed properties

### ISSUE THREAD

**Issue by jaroslavlibal** [loophp/collection#118]
Hello,

I have a question related to typed collections.

All classes in this library are final and we are expected to use the [composition pattern](https://loophp-collection.readthedocs.io/en/latest/pages/usage.html#extending-collection).

However I would like to use typed collections eg. PersonCollection as the collection of Person entities, including typehinting in business methods.

PHP Stan / PSALM generics are not enough for my use case as I would like to add some specific methods eg. AddressCollection getter to (and only to) the PersonCollection.

The implementation of my use-case seems more complicated when using composition as opposed to some AbstractCollection extension as I will have to implement all the basic CollectionInterface methods including `count()` or `getIterator()`.

I understand that this is a library concept, I just want to make sure I understand it correctly.

Or is there some possibility that hasn't occurred to me? Of course I can think of e.g. creating the mentioned AbstractCollection which will no longer be final, but I don't know if that's a conceptual solution.

Thanks!

**Comment by drupol** [comment]
Hi !

When it comes to final keywords, there are a lot of post ([#1](https://ocramius.github.io/blog/when-to-declare-classes-final/), [#2](https://matthiasnoback.nl/2018/09/final-classes-by-default-why/)) discussion about that, and I have the feeling that you've understood the concept.

Basically I do not provide an abstracted version of the Collection because I want to ship a Collection class that works well in any circumstances, with a well defined scope and business logic.

If you want, you are free to implement your own Abstract collection class (example: https://gist.github.com/drupol/c73c7b092288833d2546edaac213bea5) and start from there for sure. On that example, all the methods are implemented, it would be possible to have a reduced version of it by specifying each interface that you want to have as well instead.

Let me know if this is helping you.

**Comment by jaroslavlibal** [comment]
Hello,

thank you very much for your comprehensive reply!

I understand the reasons why it is implemented this way and will implement my own AbstractCollection class.

Thank you for your time and I hope this issue will help others who may ask a similar question in the future.
