### ISSUE TITLE
Typed collection support

### ISSUE THREAD

**Issue by raphaelvoisin** [loophp/collection#236]
Hello there :),

I'm wondering if there would be a way to support typed collection using this library (like in [ramsey/collection](https://github.com/ramsey/collection)) ?

The main goal would be to avoid repeating code like :
```php
class Customer
{
    public function addAddresses(\loophp\collection\Collection $addresses)
    {
        Assert::allIsInstanceOf($addresses, Address::class);

        // continue process ...
    }
}
```

**Comment by drupol** [comment]
Hi Raphael,

Typing the collection is one of our top priority and this is already working fine.

In your code example, you should be able to do what you want by doing:

```php
class Customer
{
    /**
     * @param Collection<int, Address> $addresses
     */
    public function addAddresses(Collection $addresses)
    {
        Assert::allIsInstanceOf($addresses, Address::class);

        // continue process ...
    }
}
```

Let us know how it goes.

**Comment by raphaelvoisin** [comment]
Sorry I've missed some explanation. I already type my collection using phpdoc like in your example, and sure it's working fine :).

I'm talking about type checking **on runtime**, which is one of the main purpose of [ramsey/collection](https://github.com/ramsey/collection, see https://github.com/ramsey/collection/wiki/Examples#typed-collection) to totally prevent adding an element of incorrect type in my collection.

Even if I have phpstan static analysis to prevent most of incorrect usages, there are cases where it's interesting to have a runtime check.

**Comment by drupol** [comment]
Oooh right !

I think this is what you're looking for: https://loophp-collection.readthedocs.io/en/latest/pages/api.html#strict

Let me know if this is ok!

**Comment by raphaelvoisin** [comment]
Unfortunately it's not exactly what I was looking for :),

`strict` raises an `InvalidArgumentException` when the collection is "consumed". I'm looking for the same behaviour but immediatly when an incorrect element is "added" to the collection (like in [ramsey/collection](https://github.com/ramsey/collection)).

To me the main benefit of strictness checking would be to detect where in the code an incorrect element is added in order to fix the behaviour.

**Comment by drupol** [comment]
Ok.

I don't think this is possible to do as of today. loophp/collection's behavior is "lazy" by default, so the behavior you're describing is perfectly normal in my opinion.

What you're looking for is a complete different behavior upon inserting elements.

You could use [squash](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#squash) but you would have to do it every time you're adding something in it. It's ugly.

Right now I don't see a solution to it but I will think about it.

**Comment by raphaelvoisin** [comment]
Thanks for your reply :).

I understand that this behaviour goes against the "lazy" capability.
I guess that my best option would be to create a `TypedCollection` decorating by composition a `loophp/collection` instance, use a proxy for all methods and overriding the behaviour of `append`, `prepend`... to do the type checking (probably using custom `Append` / `Prepend` operations), WYT ?

**Comment by drupol** [comment]
Yes technically that would be a solution... but it' going to be very cumbersome to do that because you'll have to proxy every methods/operations.

**Comment by AlexandruGG** [comment]
hey @raphaelvoisin, thank you for raising this. I've gone through the above and looked at ramsey/collection, and here are my thoughts:

> I'm looking for the same behaviour but immediatly when an incorrect element is "added" to the collection (like in [ramsey/collection](https://github.com/ramsey/collection))

Maybe I'm missing this, but I don't see where ramsey/collection does this. Looking at the [add method](https://github.com/ramsey/collection/blob/main/src/AbstractCollection.php#L55-L63) it definitely doesn't have this logic. Also, the usage of its `getType` method seems a bit inconsistent to me. For example when you use the [map](https://github.com/ramsey/collection/blob/main/src/AbstractCollection.php#L206-L209) method it types the new collection as `mixed` so you kind of lose the typing benefits (and does not do any runtime checking either).

---

Leaving ramsey/collection aside, let's look specifically at what you'd like to be able to do here, and how you can accomplish it with loophp/collection:

**1. ensure that a collection is used as a list of items of the same type known in advance**
- static analysis: you already mentioned using this 🟢 
- runtime type check: as @drupol listed, [strict](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#strict) can be used for this; although you can provide a callback function to customise how the comparison is made, you cannot specify _which type it should be expecting_ at the moment. This could be a nice addition to the operation 🟡 
- tests: together with static analysis, these should prevent your code from behaving unexpectedly ❓ 

**2. detect where in the code an incorrect element is added in order to fix the behaviour** -> to me, this sounds like something you want to have "temporarily", as in you don't need this functionality _after_ you've found the issue and fixed it (but please correct me if this assumption is wrong)
- use `strict` and either consume the collection or use [squash](https://loophp-collection.readthedocs.io/en/latest/pages/api.html#squash) to evaluate the operations. The stack trace of the exception that will be thrown should give you an indication of where the issue happened; if not, see the next point
- if the stack trace is not sufficient, you could create a wrapper around the collection which automatically applies `squash` after each operation is called (probably using the [__call](https://www.php.net/manual/en/language.oop5.overloading.php#object.call) magic method to forward the method call to the inner collection) - note I would not advocate for using this as a permanent solution because you will lose the benefits of static analysis AND of lazy evaluation, which is one of the core principles of this component; I'd only say to use it as a debugging tool if needed

I hope this helps, let me know what you think :)

**Comment by raphaelvoisin** [comment]
Hello @AlexandruGG and thank you for your complete reply :),

First :  

> Maybe I'm missing this, but I don't see where ramsey/collection does this. Looking at the [add method](https://github.com/ramsey/collection/blob/main/src/AbstractCollection.php#L55-L63) it definitely doesn't have this logic.

-> Yes it does, the `add` method just does `$this[] = $element;` which will naturally fallback on the  `offsetSet` method because the class implements `ArrayAccess`:

```php
    public function add($element): bool
    {
        $this[] = $element; // <- this calls "offsetSet" method

        return true;
    }

    public function offsetSet($offset, $value): void
    {
        if ($this->checkType($this->getType(), $value) === false) {
            throw new InvalidArgumentException(
                'Value must be of type ' . $this->getType() . '; value is '
                . $this->toolValueToString($value)
            );
        }
        // ...
    }
```

> Also, the usage of its `getType` method seems a bit inconsistent to me. For example when you use the [map](https://github.com/ramsey/collection/blob/main/src/AbstractCollection.php#L206-L209) method it types the new collection as mixed so you kind of lose the typing benefits (and does not do any runtime checking either).

-> This is quite logical to me, because this is what a `map` operation is about : mapping an **arbitrary** value (so assumed `mixed`) to each element of your collection. Other methods that are supposing to return a subset or superset or the collection (like `diff`, `intersect`, `merge` or `filter`) have a different behaviour and `clone` the instance.


**1. ensure that a collection is used as a list of items of the same type known in advance**
-> I don't necessarily expect for the same type, even if I confess that this will be 90% of my use cases. Think for example about union types (`string|Stringable`), this is why I'm perfectly ok with a closure to check the types :). This is indeed IMO something that should be added to [ramsey/collection](https://github.com/ramsey/collection).

> tests: together with static analysis, these should prevent your code from behaving unexpectedly

-> In most case, you are right. But in some case, it's not. Think about serialization/deserialization for example. You could deserialize a string to a `Collection` of object of incorrect types without a warning, even with static analysis and tests.

In the end to me, checking collection object types on runtime provides the same benefits than typehinting arguments of a function in its signature instead of phpdoc : be able to [fail fast](https://en.wikipedia.org/wiki/Fail-fast), but also as a defensive programming pattern.
To me, if you design an abstract Collection of `Address` objects and accepts this collection as a parameter of a method, you should check for types immediately :  
```php
class Customer
{
    public function addAddresses(\loophp\collection\Collection $addresses)
    {
        Assert::allIsInstanceOf($addresses, Address::class);

        // continue process ...
    }
}
```
... exactly as you would do if the argument would be a simple `array`.

Making the type checking in the Collection itself (like in [ramsey/collection](https://github.com/ramsey/collection)) sounds a valuable defensive pattern to me.

**2. detect where in the code an incorrect element is added in order to fix the behaviour**
> -> to me, this sounds like something you want to have "temporarily", as in you don't need this functionality after you've found the issue and fixed it (but please correct me if this assumption is wrong)

-> this is partially true :), because the common use case is when you missed the type in your own code and you'll see immediately in the tests. But when serialize/deserialize is in the game, or simply when you get an array of mixed values (from a controller action for example) to be transformed to a Collection, checking types immediately is a question of quality. Of course you can do the checks "all the time" (after collection creation, and at the begining of all method accepting a collection), but it's better IMO to move this check in the collection, as you usually do with "value objects".


> if the stack trace is not sufficient, you could create a wrapper around the collection which automatically applies squash after each operation is called (probably using the [__call](https://www.php.net/manual/en/language.oop5.overloading.php#object.call) magic method to forward the method call to the inner collection) - note I would not advocate for using this as a permanent solution because you will lose the benefits of static analysis AND of lazy evaluation, which is one of the core principles of this component; I'd only say to use it as a debugging tool if needed

-> I don't really like this too much as well, but this is the solution I'm trying for now (using a proxy with `__call`).

I'm however very open to the discussion because "collection object type checking" sounds a disputable behaviour

**Comment by AlexandruGG** [comment]
Thanks for clarifying those points! I'm laying out some more thoughts below, not necessarily in the order you presented them:

> Yes it does, the add method just does $this[] = $element; which will naturally fallback on the offsetSet method because the class implements ArrayAccess.

Indeed I missed this, makes sense! 😅 

> To me, if you design an abstract Collection of Address objects and accepts this collection as a parameter of a method, you should check for types immediately.

I am a big fan of defensive programming ([this talk](https://www.youtube.com/watch?v=Gl9td0zGLhw) is one of my favourites), however I would say in most cases we should not do this here, with the first reason being you will have to iterate through the collection and so lose the benefits of lazy evaluation. 

Furthermore, from what I've seen the PHP community has slowly but surely moved from runtime type checks to relying more and more (and even solely in some cases) on static analysis as it's become better in the last few years.

In fact, if we take your example and we use static analysis with fairly strict rules and levels we will get errors from both Psalm and PHPStan if we are already typing your lists/collections using the generic syntax `Collection<int, Address>` and then we attempt to add runtime type checking code. Sure, we can get around it if we use `mixed`.

> But when serialize/deserialize is in the game, or simply when you get an array of mixed values (from a controller action for example) to be transformed to a Collection, checking types immediately is a question of quality

I must say I've not had issues with deserializing because usually you have to mention the type of object you expect and the serializer will throw an exception if it cannot deserialize into that. Also, with custom list of objects like Collection you might use a custom denormalizer where you have extra type-checking logic if needed. However, I agree that there might be some legitimate cases here, especially in instances where you get a mixed array as you mentioned.

> Making the type checking in the Collection itself (like in [ramsey/collection](https://github.com/ramsey/collection)) sounds a valuable defensive pattern to me.

I completely agree, @drupol and I have had various discussions about a typed collection (like [this one](https://github.com/loophp/collection/discussions/99)) 😄. This is how we introduced the `strict` operation, which we felt was a good fit for loophp/collection based on its [principles](https://loophp-collection.readthedocs.io/en/latest/pages/principles.html).

The way I see it, the main things we need to solve if we want something different are:
- when exactly should the type check happen? For which operations? Or for all?
- how does this fit with lazy evaluation?
- how do we type-hint things? For example, the `append` operation already has type hints in place that do not allow adding a different type to the collection if the collection is already instantiated with a single type or typed as such (see [the type checks](https://github.com/loophp/collection/blob/master/tests/static-analysis/append.php#L74-L77)). So if we want to add runtime type-checking logic in place we might need to allow `mixed` in the type system

**Comment by raphaelvoisin** [comment]
> Furthermore, from what I've seen the PHP community has slowly but surely moved from runtime type checks to relying more and more (and even solely in some cases) on static analysis as it's become better in the last few years.

I agree with that, and I think that nowadays, as soon as you use phpstan/psaml (and everyone should IMO :D), it's less legitimate to add runtime checks that couldn't be fully covered by static analysis.

However to me, there are still some legitimate use-cases where runtime type checking is still mandatory, but probably most of them are related to serialization, or when you don't fully control (via vendor / middleware for example) the calling code.

The thing is, when we design a class, we shouldn't care too much about where it will be used, so I prefer to apply defensive programming as much as possible everywhere (of course this is more important in a library than in an application) and be able to fail fast to facilitate debugging.

> I must say I've not had issues with deserializing because usually you have to mention the type of object you expect and the serializer will throw an exception if it cannot deserialize into that. Also, with custom list of objects like Collection you might use a custom denormalizer where you have extra type-checking logic if needed. However, I agree that there might be some legitimate cases here, especially in instances where you get a mixed array as you mentioned.

This is true, but :  
- i think it's not that easy to write the tests that would prevent a serializer to not deserialize into the object if the object itself don't enforce the types on runtime
- there is a low support for generics in serializer (extractors) for now AFAIK, especially when we are talking about nested generics 

> I completely agree, @drupol and I have had various discussions about a typed collection (like https://github.com/loophp/collection/discussions/99) smile. This is how we introduced the strict operation, which we felt was a good fit for loophp/collection based on its [principles](https://loophp-collection.readthedocs.io/en/latest/pages/principles.html).

Thank you for the links ! I see that it has been discussed as we do now :). And I fully agree that runtime type check is not compatible with lazyness.

> when exactly should the type check happen? For which operations? Or for all?

To me, that would be immediately on all operations involving adding an element of the same type, not for all operations. So it would involve all static constructors + `append`, `associate`, `combine` (?), `foldXXX`, `merge`, `prepend` (I probably missed some)... Some operations like `map` should not be involved (so create a non-typed collection), and other operations like `flip` should probably just not exist -> this advocate for a different class (`TypedCollection`) if we would want that I think, so it's maybe out of the scope of this library.  

> how does this fit with lazy evaluation?

I just don't think it's compatible by design. However, we could keep lazyness on all operations not involving adding a new element.

> how do we type-hint things? For example, the append operation already has type hints in place that do not allow adding a different type to the collection if the collection is already instantiated with a single type or typed as such (see [the type checks](https://github.com/loophp/collection/blob/master/tests/static-analysis/append.php#L74-L77)). So if we want to add runtime type-checking logic in place we might need to allow mixed in the type system

I guess that we can keep the same template and typehint with `Collection<MyType>`. That would be a duplicate of what is done  on runtime as most usually do when dealing with an `array` as argument :  
```php
    /**
     * @param array<DateTimeInterface> $dates
     * @return void
     */
    public function doSomething(array $dates): void {
        \Webmozart\Assert\Assert::allIsInstanceOf($dates, DateTimeInterface::class);
        
        // continue process
    }
```
-> But I think this is all this debate is about : is the check `\Webmozart\Assert\Assert::allIsInstanceOf($dates, DateTimeInterface::class);` really relevant in 2022 :smile: ...?

**Comment by AlexandruGG** [comment]
> this advocate for a different class (TypedCollection) if we would want that I think, so it's maybe out of the scope of this library.

Indeed Pol and I felt the same, too much would have to change to make all of these things work with the current implementation.

> But I think this is all this debate is about : is the check \Webmozart\Assert\Assert::allIsInstanceOf($dates, DateTimeInterface::class); really relevant in 2022 😄 ...?

Technically in your example that will not work with static analysis because you'll get an error saying that `$dates` is already a list of `DateTimeInterface` objects, so you'd have to add a manual ignore 😬.

So the alternatives would be:

A)

```PHP
/**
* @param array<mixed> $dates  <-- note we allow mixed here
* @return void
*/
public function doSomething(array $dates): void {
  \Webmozart\Assert\Assert::allIsInstanceOf($dates, DateTimeInterface::class);
  
  // continue process
}
```

B)

```PHP
/**
 * @return void
 */
public function doSomething(DateTimeInterface ...$dates): void {
    // assertion no longer needed
    
    // continue process
}
```

Note that while A) is correct, IMO it's not ideal when we can take advantage of static analysis. And B) is only possible because we were using `array` there before, so we can technically substitute that with variadics and the language will enforce the type for us (but obviously you cannot do this if using a collection object).

Who knows maybe proper generics support will land in PHP some day and all of this will be solved, but until then we have a few "workarounds" to choose from.

**Comment by AlexandruGG** [comment]
> Actually we can!

Oh right, I forgot you can spread iterators as well and I actually used that in the past 🤦‍♂️. So I guess that's a somewhat viable alternative, but I think you lose the lazy evaluation benefits, right?

**Comment by AlexandruGG** [comment]
Hey @raphaelvoisin, same on this one, do let us know if you feel it should be kept open.
