### ISSUE TITLE
Consider adding a comparison with this library and similar collection libraries

### ISSUE THREAD

**Issue by aszenz** [loophp/collection#33]
Thanks for creating this library, the Readme lists similar collection libraries as inspiration, I think it would be really helpful for the project to also highlight the key points that distinguish it from these libraries.

I think a few notes about differences in api design between the libraries would be quite useful and help people decide which one to pick.

I would especially like to know how this library compares to https://github.com/DusanKasan/Knapsack and https://github.com/mtdowling/transducers.php

**Comment by drupol** [comment]
Hi,

Indeed, it would be nice to do.

This library is different from others because:

* It tries to use S.O.L.I.D. principles everywhere, notice how each single "method/operation" live in its own class file and could be tested on its own. It's fully based on classes and interfaces, there is no function defined in the global scope, I really wanted to avoid that.
* It almost fully statically typed (with Psalm: _currently ~95%_) and PHPStan is set to the max level, score are pretty good.
* It implements more than 80 operations. Operations are usually "bidirectional" (_I don't know if its the proper wording here_), e.g.: _pair_ and _unpair_, _window_ and _unwindow_, _wrap_ and _unwrap_, _zip_ and _unzip_... etc etc
* Each method/operations returns a new Collection, there are only 2 methods (_Collection::current() and Collection::key()_) that returns a single value.
* "_It eats its own dog food_", some operations are constructed by composing, assembling different other operations (_like Truthy, Falsy, Nullsy... and many others_).
* It's like Lego, you could imagine doing something completely different with the operations classes, which are completely standard. The Collection library is just "one" of the things you can do with that.
* It's newer, up-to-date and thoroughly tested with `PHPSpec`, baked with `Infection` to make sure that tests are properly written. We could improve the tests by testing each operation classes, but right now this is not the priority.
* It's easy to get into the code. Wants to contribute? Something is missing? Easy, just read the changelog, pick an existing commit where I introduce a new operation, read it and 5 minutes later you'll be ready to hack the code and hopefully submit a PR :-)
* Miscellaneous: "Changelog" and "changelog per release" is automatically created with Github actions, I don't do anything, everything is automated.
* Miscellaneous: Documentation is also automatically rebuild automatically
* Last but not least: It's used in production by a couple of people that I know at work and outside work as well

I guess I could improve the list by the time and I probably forgot some stuff, but it gives you already a pretty good starting point.

Keep in mind that each open-source library I publishes is a way for me to be kept up to date with new development techniques and it's important for me to maintain them to ensure that I am up to date.

**Comment by aszenz** [comment]
Thanks for the detailed explanation, indeed I see that the library uses quite a few best practices.
My intention was to highlight the design differences between the libraries like:

1. Everything is a class in this library as you mentioned while https://github.com/DusanKasan/Knapsack also provides collection functions

2. Is there any concept of transducers in the library, I see a code snippet that highlights how to decouple the input data from the transformations in the readme by providing the data last but the example also shows collection class static constructors like `fromIterable` that take data first so they are not `data-last function-first` approaches, right ? 

```php
<?php

$data = ['foo', 'bar', 'baz'];
$filterCallback = static fn(string $userId): bool => 'foo' !== $userId;

// Using the Collection library  
$collection = Collection::fromIterable($data) // --EDIT: This one is data first approach it seems
    ->filter($filterCallback)
    ->reverse();
print_r($collection->all()); // ['baz', 'bar']

// Using single operations. --EDIT: This one uses data last functions first
$filter = Filter::of()($filterCallback);
$reverse = Reverse::of();
$pipe = Pipe::of()($reverse, $filter);
print_r(iterator_to_array($pipe(new ArrayIterator($data))));  // ['baz', 'bar']
```

**Comment by drupol** [comment]
Thanks!

>     1. Everything is a class in this library as you mentioned while https://github.com/DusanKasan/Knapsack also provides collection functions

Yes, it's only one class and everything (_or mostly_) is dumped in it. I didn't say it was right or wrong, I would say that I prefer to split concerns and have smaller chunk of code to deal with. I prefer flexibility and modularity. This is also why open-source is great, you choose what fits you best :-)

My library is sold as a Collection library, but the core, the heart of it it is the Operations classes. What does the main Collection class is just providing a friendly interface for users and then calling, composing and assembling the Operations classes, nothing else.

>     2. Is there any concept of transducers in the library, I see a code snippet that highlights how to decouple the input data from the transformations in the readme by providing the data last but the example also shows collection class static constructors like `fromIterable` that take data first so they are not `data-last function-first` approaches, right ?

Indeed. The Collection class provide a user friendly interface. Easy to use. It doesn't follow "_function-first-data-last_". However, all the internals, all the operations are (_you spotted it in the example_) ! We could perfectly imagine writing another Collection class using that scheme, it would be very quick and easy to do. Actually, I like the idea, but I think that people in PHP (_which is not really a functional programming language_) are more used to use "_data-first-function-last_", this is why I choose to write it this way.

**Comment by aszenz** [comment]
Thanks for providing your thoughts, I agree comparison isn't the right word for it, what I intended to know was what was the motivation and design goals for the library and what distinguished it from others. 

I think php syntax doesn't lend itself well to `data-first-function-last` approach compared to the builder pattern, still glad to see the operation classes can be composed directly.

Anyways now that you have provided your input on it, I'll close this issue.
